In [2]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt 

In [3]:
m = np.random.randint(7,10,20)

In [4]:
print(m)

[8 7 9 8 7 7 9 7 7 7 8 7 9 9 8 8 7 9 9 7]


In [5]:
np.mean(m)

7.85

In [6]:
np.median(m)

8.0

In [7]:
# Mode is not a part of numpy library need to import from statistics library.

In [8]:
from statistics import mode 

In [9]:
mode(m)

7

In [11]:
# Population in statistics - It is consider as considered as the total observation that is made. 
# Sample in statistics - It is nothing but  a subset of population so that we would able to interperate it.

In [14]:
population = np.random.randint(10,20,100)

In [15]:
population

array([18, 15, 14, 16, 14, 10, 13, 18, 18, 17, 12, 13, 17, 14, 10, 10, 14,
       14, 13, 18, 17, 11, 15, 19, 17, 17, 14, 18, 18, 17, 10, 18, 10, 12,
       18, 15, 16, 17, 10, 19, 16, 12, 11, 11, 14, 19, 12, 13, 16, 12, 17,
       12, 14, 14, 15, 16, 10, 18, 11, 17, 14, 11, 13, 13, 12, 13, 12, 16,
       15, 18, 14, 16, 19, 16, 10, 16, 15, 14, 18, 13, 17, 17, 19, 10, 17,
       19, 10, 17, 14, 10, 15, 15, 12, 12, 16, 13, 10, 11, 17, 16])

In [16]:
np.mean(population)

14.51

In [17]:
np.median(population)

14.5

In [18]:
mode(population)

17

In [19]:
sample = np.random.choice(population, 20)

In [20]:
sample

array([13, 14, 18, 15, 16, 17, 15, 16, 12, 17, 10, 12, 13, 15, 14, 16, 15,
       16, 17, 12])

In [21]:
np.mean(sample)

14.65

In [22]:
np.median(sample)

15.0

In [23]:
mode(population)

17

In [24]:
sample_1 = np.random.choice(population, 15)
sample_2 = np.random.choice(population, 15)
sample_3 = np.random.choice(population, 15)
sample_4 = np.random.choice(population, 15)

In [28]:
all_samples = [sample, sample_1,sample_2,sample_3,sample_4]
sample_mean=[]

for i in all sample:
    sample_mean.append(np.mean(i))

sample_mean

SyntaxError: invalid syntax (2085768897.py, line 4)

In [29]:
all_samples = [sample, sample_1, sample_2, sample_3, sample_4]
sample_mean = []

for i in all_samples:
    sample_mean.append(np.mean(i))

sample_mean

[14.65,
 14.933333333333334,
 14.733333333333333,
 14.933333333333334,
 14.333333333333334]

In [30]:
np.mean(sample_mean)

14.716666666666665

In [31]:
np.median(sample_mean)

14.733333333333333

In [32]:
mode(sample_mean)

14.933333333333334